### ISSUE TITLE
Right-click menu in back books doesn't do anything

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#1066]
v.2.7.35 
I'm trying to tweak a paragraph in the GLO book.
I've "expanded to 106%" I've "expanded +2 lines" but the output is identical to what it looks like if nothing is applied.

Also, it is impossible to remove (Reset) those additions. (At least I haven't figured it out yet.) 
"RESET > paragraph" doesn't do anything. Nor does "Reset > page". 

Sometimes applying the opposite setting gets it back to "zero tweaks" (100%) but sometimes even that doesn't seem to work.

**Comment by davidc86** [comment]
Update. the Right-click menu won't show up on my exported XXA book. It works (or shows up at least) on my XXB book. The difference? The XXA is only exporting chapter 28, nothing else. Does skipping the first 27 chapters mess up PTXprint's non-scripture location tracking?

**Comment by markpenny** [comment]
This should be working as expected in 2.7.36 when it is released later today.

**Comment by davidc86** [comment]
[SLU-PublikasiLiturgiSelaruPTXprintArchive.zip](https://github.com/user-attachments/files/19650955/SLU-PublikasiLiturgiSelaruPTXprintArchive.zip)

Well, I'm not sure what all is going on, but the right-click menu still doesn't work for most of this output. 
Possibilities: 
* we are using user-defined usfm
* lots of tables (in the second book) and apparently tables don't show a right-click menu

**Comment by markpenny** [comment]
This seems to be working better now in recent versions, 2.8.8+ but may not be perfect/ideal for non-scripture books.

![Image](https://github.com/user-attachments/assets/48f0edca-5dd7-4bbc-9537-39b12b5bfd8c)
