### ISSUE TITLE
Text under introduction is not aligned to grid

### ISSUE THREAD

**Issue by jeffheath-sil** [sillsdev/ptx2pdf#163]
I noticed that normal text that falls under an introduction is not aligned to the grid. If I just have titles, the grid alignment is maintained, but if there is an introduction, the text below the introduction does not seem to be aligned. I'm not sure if this image will help, but holding a ruler along the baseline of text under the intro doesn't line up in the page to the right:
![image](https://user-images.githubusercontent.com/14953913/89530339-3d5a4f00-d7e6-11ea-8180-82887447977e.png)

I didn't have this problem in my last typesetting job, as the introductions were all on separate pages. So maybe this has never been possible. But it seems like just as the grid is maintained below titles, it should also be maintained below the introduction.

Any chance the intro paragraphs can just get lumped in together with the titles and processed the same way? Actually, I just tried that - I added "\TextType Title" to the introduction styles, and it appears that they are now included in the title processing, and the text below it is back on the grid! Does that sound like the right way to address this problem?

**Comment by davidg-sil** [comment]
I've noticed what you're reporting as well, so it's good to have this issue to keep track of it.
There is something funny going on between MH's new gridding mechanism (controlled by \squashgridbox or something similar) and titles. Confusingly, it *only* seems to affect the title page of a book, not a normal section heading, even though both are \TextType title.
As for putting introductions into the title, that doesn't sound like an ideal way as (a) items within the title box are not normally grid-aligned (relative to other pages) and (b) the title box is not allowed to split across pages, as far as I know.

**Comment by davidg-sil** [comment]
Using this issue to record my findings.  Running ptxprint-JHNWEBorig.tex from the tests. 
**Extracts from (normal) log:** (grid alignment: good)
Baselineskip for p undefined, set to 14.99484pt
before gridbox: ht0=48.96985pt; dp0=0.0pt(0.0pt); spacebefore=0*1.07106pt; depth=0.0pt
after gridbox: skip 0.0pt, kern 11.00952pt; baselineskip=14.99484pt
Box height for sg column part of page: **74.974pt**

**Extracts from log with added "\ip testing"** (grid mis-alignment approx 1ex)
Gridbox output as before. Box height (for sg colum part of page): **94.8pt.**

 additional box contents:
```
..............\penalty 10000
..............\glue(\parfillskip) 0.0
..............\glue(\rightskip) 0.0 plus 352.8142
.............\penalty 10000
.............\glue 4.28424
............\penalty 10000
............\glue(\parskip) 0.0
............\glue(\baselineskip) 1.83076
............\hbox(13.16408+4.83577)x352.8142, glue set 311.17654fil
.............\hbox(0.0+0.0)x0.0
.............\beginL
.............\pdfsavepos
.............\write0{\noexpand \@parstart {\the \pdflastxpos }{\the \pdflastypo
s }}
.............\endL
.............\kern 9.03374
.............\font<h-12> testing
.............\beginL
.............\pdfsavepos
.............\write0{\noexpand \@parend {\the \pdflastxpos }{\the \pdflastypos 
}}
.............\endL
.............\penalty 10000
.............\glue(\parfillskip) 0.0 plus 1.0fil
.............\glue(\rightskip) 0.0
............\penalty -100
............\glue 14.99484
...........\hbox(0.0+0.0)x0.0
...........\glue 0.0 plus 1.0fil
..........\kern 0.0
..........\glue 0.0 plus 1.0fil
.......\glue(\lineskip) 0.0
```
So my initial question was: why is it using ```\font<h-12>```  for  \ip text?, but that's a wild goose chase, because \p text is also recorded as ```\font<h-12>```, I therefore assume that this is just font-caching in action.  So why does additional line cost 23.8pt ext

**Comment by davidg-sil** [comment]
Issue is the depth of the \ip text not being accounted for in the transition to 2column mode.
Fix committed.

**Comment by jeffheath-sil** [comment]
@davidg-sil I pulled your fix and tested it, but it doesn't seem to align the text beneath the intro for me. In the test I have an \imt1 and a couple of \ip's. It was just the few lines changed in ptx-para-style.tex and paratext2.tex, correct?

But even if it were fixed, I might go back to marking the intro styles as titles anyway, because they are a smaller font, and I sort of like the fact that the lines aren't aligned to the grid, with the larger line spacing.

**Comment by davidg-sil** [comment]
So you're adjusting the baseline too? then yes, as long as you never cross
a page boundary then making it a title would put the text below on grid. in
fact it's the only way I can think of that working. I do't think theres any
other code to recover the grid

**Comment by jeffheath-sil** [comment]
In my testing, if you **don't** mark the intro styles as titles, the text below the introduction is **still** not aligned to the grid (with macros as of yesterday).

**Comment by jeffheath-sil** [comment]
I realized that 0.9.2 has been released, so I tried again with that version. It seems to be better (closer to on the grid), but I'm still seeing some variation. For example:
![image](https://user-images.githubusercontent.com/14953913/89988919-1bdee480-dc78-11ea-8afd-6991153fe50d.png)

I intentionally cut this screen shot off at the bottom. You can see in the left column, it goes right along the baseline (and cuts of descenders). In the right column, it's cutting off the bottom part of letters.

So I don't think this has been completely resolved yet. (But may be "close enough" for PTXPrint version 1???)

**Comment by mhosken** [comment]
Assuming that the intro paragraphs and headings are all part of a single title block, then, yes, it looks like there is still some work to be done here. If OTOH the intro paragraphs are body text, then all bets are off if their line spacing is not grid aligned. The macros do not do any grid alignment of body text.

**Comment by jeffheath-sil** [comment]
OK, here's my analysis. I'm running a test with a couple of \mt lines, then an \imt1 and a couple of \ip's, before the normal text (\c, \s1, \p, \v...)  It looks like the intro text \ip lines use the grid spacing, like normal text. So it assumes that the text before the \ip's is aligned to the grid, and those lines just need to be laid down on the page. But it appears that the \imt1 is being a bad boy and not ending on the grid. If I put the following in mods.sty:
```
\Marker imt1
\TextType Section
```
then the \ip lines and the text afterwards line up properly to the grid, because the \imt1 is now being treated as a section heading which makes sure that the block laid down uses a multiple of the grid size.

But I'm not sure what the solution should be. In usfm.sty it looks like all the intro styles are \TextType Other. Should styles of that type always use the grid spacing? If the \imt1 is too tall should it automatically lay itself down to take up 2 lines?

(I'm happy with my solution for the current project, pending approval, of making intro style \TextType's into Title or Section, since I don't really want the intro text with its smaller font size to be aligned to the same grid anyway. All intros are small enough to not need a page break.)

**Comment by mhosken** [comment]
\TextType Other is used in too many places for us to infer anything interesting for it. I think there are two ways forward:

- report an issue on usfm.sty and hopefully have it fixed or else find out why it shouldn't
- ship our own ptxprint.sty that sits between usfm.sty and custom.sty

**Comment by mhosken** [comment]
OK in dev/ I have add ptx2pdf.sty to the src/ directory which is stitched to be imported immediately after usfm.sty.

**Comment by jeffheath-sil** [comment]
I think that should do the trick. (I don't really want to checkout dev/, so I'll wait until it is released to test it.)
