### ISSUE TITLE
Font size in footnote area

### ISSUE THREAD

**Issue by viverechristus** [sillsdev/ptx2pdf#96]
I'm having a problem with how PTXprint changes the fontsize of certain tags that routinely show up in footnotes.

All our footnote-related tags are set to **\FontSize 12** as per usfm.sty. These values are not changed in either PrintDraft-mods.sty or custom.sty.

In PTXprint (0.7.0) I have set the Footnotes & Cross-references font size to 8 pt (Head+Foot tab), while the main Layout tab font is set at 11 pt.

![image](https://user-images.githubusercontent.com/915182/83498104-ad4a1180-a4e5-11ea-99a8-c823db2aa2c0.png)

There are two undesirable results:

(1) Text marked with \xta tag in footnotes is ugly big:

![image](https://user-images.githubusercontent.com/915182/83498501-33665800-a4e6-11ea-985a-35ec86eb9334.png)

(2) References marked with \xt tag in the glossary text (where we have non-footnote references) is footnote sized:

![image](https://user-images.githubusercontent.com/915182/83498762-84764c00-a4e6-11ea-9c1f-7f69f54d6448.png)

I think I can solve this by simply stripping out the \xta and \xt tag in PrintDraftChanges.txt. But it might be nice to have this working "naturally."

**Comment by viverechristus** [comment]
I confirmed that I can strip out \xt and \xta, but with the undesirable consequence that there's the boldface from the \xo marker targets the entire line, so there's no more contrast between the (boldface) target reference and the (regular) cross-reference.

![image](https://user-images.githubusercontent.com/915182/83499403-82f95380-a4e7-11ea-927a-f08a460c62df.png)

So another solution would be handy. Thanks!

**Comment by viverechristus** [comment]
A related issue is that we mark up foreign language text (e.g., Khmer), which we use in footnotes and glossary entries to explain some of our target language words. This text is marked up with a custom namespace marker \zkh...\zkh*.

If we define this marker in custom.sty with \FontSize 12, then it shows up full size in footnotes (see the big text at the top right of the footnote in the previous post). If we leave out the \FontSize definition, then when it shows up in the glossary (ordinary text) it is rendered much smaller than surrounding text.

Is there a solution (other than using different tags depending on whether we are in the footnote or the glossary)?

**Comment by markpenny** [comment]
This is now fixed in 0.7.2 for general markers (footnote and x-ref markers). So the \xt in footnotes will match the rest of the text, and the \xt in main text (or intros) will match that body test. We may be able  to do something for other \xyz ...character... \xyz* styles, but that won't be until the end of the week.

**Comment by viverechristus** [comment]
Related issue (and more serious than \z... markers):

The footnote and cross-reference caller in the footnote area does not scale with the footnote font size, but gets its size from the body. In the following screenshot, I've exaggerated the effect by making the footnote font size 6 and leaving the body font size at 11 or 12:

![image](https://user-images.githubusercontent.com/915182/84235338-e4d93f00-ab1f-11ea-903e-16a6f348b691.png)

I think the desired behavior would be for the caller in the text to match the body font size, and the corresponding caller in the footnote area to scale down to the footnote area size. (Right now I'm using about a 3 point spread between body and footnote area, so it's obvious, though not as glaring as in the screenshot.)

**Comment by mhosken** [comment]
We've done a lot of work in this area so please re-test with 0.8.2 when it arrives

**Comment by mhosken** [comment]
In particular, as of 0.8.2, if you want to make the font size of a character style dependent on the text around it, you will want to use \FontScale. It has the advantage that it takes precedence over \Fontsize. So:
```
\Marker wj
\FontScale 1
\Color 128
```

As for styling footnote callers, you can set the style of the in text caller by setting a style for it using \CallerStyle and the in note caller by setting a style for that using \NoteCallerStyle as in:

```
\Marker f
\CallerStyle fcaller
\NoteCallerStyle fncaller

\Marker fcaller
\StyleType Character
\Color x000080

\Marker fncaller
\StyleType Character
\FontScale 0.9
\Bold
\Color x008000
```

**Comment by davidg-sil** [comment]
From 0.8.2, \+wj, etc. should now work "properly"  in XeTeX, at least. 
At least, assuming that 'properly' means 'keep current character styling as base, superpose any new bits from marker wj (etc) that are different to \p'

I don't know if ptxprint is still removing the +.

**Comment by davidc86** [comment]
Woohoo! 
\FontScale  1
Sweet! Nice trick for getting the usfm.sty to not be so bossy. Worked perfectly for my +\wj footnotes. Very nice.

**Comment by viverechristus** [comment]
In 0.8.2, something (I assume the fontsize fix) has broken the function whereby the callers/callees are generated. Here's the dialogue window (footnotes are Roman letters, cross references are Khmer letters):

![image](https://user-images.githubusercontent.com/915182/85246935-6614c800-b476-11ea-9086-a7c5550e632d.png)

Here's a sample output. You'll see that only plus signs are generated as callers/callees, whether for footnotes or cross references:

![image](https://user-images.githubusercontent.com/915182/85247070-d15e9a00-b476-11ea-9e2f-993a54fb01c8.png)

(On the plus side -- no pun intended, but there it is! -- the font size problem appears to be resolved.)

**Comment by viverechristus** [comment]
The caller/callee problem seems to be resolved in 0.8.4! Thanks.

**Comment by viverechristus** [comment]
I'm afraid I'm still getting the sizing problem. I added the following code to PrintDraft-Mods.sty:

```
\Marker f
\CallerStyle fcaller
\NoteCallerStyle fncaller

\Marker fcaller
\StyleType Character
\FontScale 1

\Marker fncaller
\StyleType Character
\FontScale 1
```

But I'm still getting oversized callees in the footnote area (see below). It's more than likely that I've misunderstood how to implement the solution!

![image](https://user-images.githubusercontent.com/915182/85406045-6c489880-b58b-11ea-80e3-af28836bcec1.png)

**Comment by davidg-sil** [comment]
Have you tried adjusting the  relevant \FontScale  to 0.7 or so? It ought to work!

**Comment by mhosken** [comment]
Or set \Superscript. Also think about using \NoteCallerRaise which looks like it has been set.

**Comment by viverechristus** [comment]
>  if you want to make the font size of a character style dependent on the text around it, you will want to use \FontScale

I understood that to mean that if \FontScale for fncaller is set to "1", then it will scale down to the size of the footnote text around it (which can be set to anything in PTXprint).

If it has to be manually scaled down in the stylesheet, it seems that the issue is ameliorated but not solved: ameliorated since I now have control via the stylesheet, unsolved because the callee still doesn't scale in relation to the footnote text size (defined in PTXprint) but in relation to the main text size.

(But maybe I still don't fully understand the solution! :)

**Comment by mhosken** [comment]
Perhaps just try it, before extending this issue with your attempts to guess what it does.

\FontScale 1 says "Don't use your \FontSize, just use the fontsize of the text you are a character style within". I.e. do the right thing.

Try it and see if it works, and then let us know whether we can close this issue. Thank you.
