### ISSUE TITLE
PTXprint does not remember the specified picture (c) text from one session to the next

### ISSUE THREAD

**Issue by davidc86** [sillsdev/ptx2pdf#986]
This might be related to #985, but maybe not. 

ISSUE: If I add (c) text to pictures and exported the PDF, they will show up (somewhat) nicely, BUT when I exit and reopen PTXprint, those settings are gone. It does not remember the specified picture (c) text from one session to the next.

**Comment by davidc86** [comment]
Well, I know it is not related to #987 because the SIZE of the (c) box now works nicely and we can propagate a setting across all similar illustrations, but IF I close PTXprint and reopen it, even after Saving all through the process, all (c) text settings are completely deleted.

**Comment by mhosken** [comment]
This is probably fixed now that we write the picchecks files in the right place

**Comment by davidc86** [comment]
I don't know if this is fixed or not. I just tried 2.6.8 and got this immediately on clicking Print:

![Image](https://github.com/user-attachments/assets/e49ef3d3-564a-46a5-9638-e6fa4db86e2d)

I have not changed any USFM in this file. I just trying to get PTXprint to reproduce what we had before the overhaul of the Picture tab.

**Comment by davidc86** [comment]
Here is the dump from the error: 

This is XeTeX, Version 3.141592653-2.6-0.999995 (TeX Live 2023) (preloaded format=xetex 2023.8.18)  24 OCT 2024 16:16
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**SLU_PublikasiSelaru-Rut_RUT_ptxp.tex
(c:/My Paratext 9 Projects/SLU/local/ptxprint/PublikasiSelaru-Rut/SLU_PublikasiSelaru-Rut_RUT_ptxp.tex (c:/Program Files/PTXprint/ptx2pdf/paratext2.tex This is xetex "0" "999995"
\@ndhooks=\toks13
\st@rtptxhooks=\toks14
\@ndptxhooks=\toks15
\@nithooks=\toks16
\@idhooks=\toks17
\@veryparhooks=\toks18
\@veryparstarthooks=\toks19
\p@rstylehooks=\toks20
 (c:/Program Files/PTXprint/ptx2pdf/ptx-constants.tex) (c:/Program Files/PTXprint/ptx2pdf/ptx-utility.tex
\s@vedeofdepth=\count28
\usedm@rks=\toks21
) (c:/Program Files/PTXprint/ptx2pdf/ptx-tracing.tex
\TRACEcount=\count29
) (c:/Program Files/PTXprint/ptx2pdf/ptx-diglot.tex
\diglotDbgJoinboxes=\count30
 Special penalty dgl@tPenColSwap is -10002 Special penalty dgl@tPenInternalRpt is -10003 Special penalty dgl@tPenLtrialEnd is -10004 Special penalty dgl@tPenRtrialEnd is -10005
\diglotLho@ks=\toks22
\diglotRho@ks=\toks23
\FontSizeUnitL=\dimen20
\FontSizeUnitR=\dimen21
\le@dingunitL=\dimen22
\le@dingunitR=\dimen23
\onel@neunitL=\dimen24
\onel@neunitR=\dimen25
\verticalsp@ceunitL=\dimen26
\verticalsp@ceunitR=\dimen27
\IndentUnitL=\dimen28
\IndentUnitR=\dimen29
\p@rlinesgone-L=\count31
\p@rlinesgone-R=\count32
\curr@djparL=\count33
\curr@djparR=\count34
\p@rnumL=\count35
\p@rnumR=\count36
\@numcutsL=\count37
\@numcutsR=\count38
\dropped@ther@linesL=\count39
\dropped@ther@linesR=\count40
\n@xtpartialNrml=\box20
\n@xtpartialRev=\box21
\galleyexc@ss=\box22
\wholeL=\box23
\partialL=\box24
\excessL=\box25
\excessR=\box26
\wholeR=\box27
\partialR=\box28
\trialbox=\box29
\savedpenalty=\count41
\tmpcount=\count42
\curactivecols=\count43
\Lboxpenalty=\count44
\Rboxpenalty=\count45
\partialLpenalty=\count46
\partialRpenalty=\count47
\endtri@lpen@lty=\count48
\chunkpenalty=\count49
\lastchunkpenalty=\count50
\@bls=\dimen30
\columnLwidth=\dimen31
\columnRwidth=\dimen32
\availhtL=\dimen33
\availhtR=\dimen34
\availht@com=\dimen35
\chunkDelta=\dimen36
\p@geChunkDelta=\dimen37
\baselineDelta=\dimen38
\baselineDeltaL=\dimen39
\baselineDeltaR=\dimen40
\thisjointDelta=\dimen41
\cumulativeDeltaL=\count51
\cumulativeDeltaR=\count52
\cumulativeDelta=\count53
\adjustp@ge=\dimen42
\@ftergalleyskip=\dimen43
\Lht=\dimen44
\Rht=\dimen45
\TempDim=\dimen46
\Lbox=\box30
\Rbox=\box31
\MaxPages=\count54
\topchunk=\box32
\botchunk=\box33
\notechunk=\box34
\triall@@pcount=\count55
) (c:/Program Files/PTXprint/ptx2pdf/ptx-para-style.tex
\l@stparbadness=\count56
\c@rrentcols=\count57
\headingtopspace=\skip18
\headingmidspace=\skip19
\he@dingbox=\box35
\upwardsHackDiff=\dimen47
\lastdepth=\dimen48
\dropped@ther@lines=\count58
\p@rlocs=\write0
\readp@rlocs=\read1
\prev@y=\count59
\this@y=\count60
\thing@y=\count61
\tmp@lines=\count62
\thispar@lines=\count63
\p@rlinesgoneMonoglot=\count64
\pr@vdelay=\count65
\th@sdelay=\count66
\j@nkbox=\box36
\tmpctsb@x=\box37
\ch@pterwd=\dimen49
\ch@pterbox=\box38
\ch@pternote=\box39
\str@tbox=\box40
\tagCount=\count67
) (c:/Program Files/PTXprint/ptx2pdf/ptx-char-style.tex
\f@ntl@g=\write1
\end@box@run=\toks24
\start@box@run=\toks25
\minfontsize=\dimen50
\ulb@x=\box41
\n@tenesting=\count68
\p@ranesting=\count69
) (c:/Program Files/PTXprint/ptx2pdf/ptx-milestone-style.tex
\tmpt@ks=\toks26
\it@mcount=\count70
\afterwordpages=\count71
\num@rgs=\count72
\ISBNfontdim=\dimen51
) (c:/Program Files/PTXprint/ptx2pdf/ptx-note-style.tex
\n@tecl@sses=\toks27
\n@teid=\count73
\AboveNoteSpace=\dimen52
\InterNoteSpace=\dimen53
\NoteCallerWidth=\dimen54
\NoteCallerSpace=\dimen55
\he@dingnotes=\box42
\t@blenotes=\box43
\n@tetmp=\box44
\d@note=\toks28
\currn@tetparnum=\count74
\endn@teclasses=\toks29
\plac@ndnotes=\toks30
\f@@tstrut=\box45
\AboveEndNoteSpace=\dimen56
\n@tewidth=\dimen57
\lastnoteinterlinepenalty=\count75
\lastnoteparpenalty=\count76
\lastnotewidowpenalty=\count77
\lastnoteclubpenalty=\count78
\internoteskip=\skip20
\noteRag=\skip21
\xr@fbox=\box46
\XrefB@x=\box47
\XrefSkip=\dimen58
) (c:/Program Files/PTXprint/ptx2pdf/ptx-stylesheet.tex
\pstr@t=\box48
\dropnumbersize=\dimen59
\dropnumberraise=\dimen60
\v@rsehooks=\toks31
\prev@rsehooks=\toks32
\gr@btoks=\toks33
\styl@sheet=\read2
\origb@selineskip=\dimen61
 Special penalty book@ndpenalty is -10006 Special penalty sect@ndpenalty is -10007
\t@stread=\read3
\AdjListPath=\toks34
\PicListPath=\toks35
\TrigListPath=\toks36
\PtxFilePath=\toks37
\do@ctive=\toks38
ch> DefineActiveChar: 91
ch> DefineActiveChar: 40
\c@th@@ks=\toks39
\afterh@@ks=\toks40
\FontSizeUnit=\dimen62
\IndentUnit=\dimen63
\PaperWidth=\dimen64
\PaperHeight=\dimen65
\MarginUnit=\dimen66
\BindingGutter=\dimen67
\TitleColumns=\count79
\IntroColumns=\count80
\BodyColumns=\count81
\le@dingunit=\dimen68
\onel@neunit=\dimen69
\verticalsp@ceunit=\dimen70
\topm@rgin=\dimen71
\bottomm@rgin=\dimen72
\bmg@p=\dimen73
\textwidth=\dimen74
\textheight=\dimen75
\colwidth=\dimen76
\ExtraRMargin=\dimen77
\gutter=\dimen78
\XrefNotesWidth=\dimen79
\XrefNotesMargin=\dimen80
) (c:/Program Files/PTXprint/ptx2pdf/ptx-periph.tex
\periphdepth=\count82
\an@nymousperiphs=\count83
) (c:/Program Files/PTXprint/ptx2pdf/ptx-attribute.tex) (c:/Program Files/PTXprint/ptx2pdf/ptx-references.tex
\c@untA=\count84
\c@untB=\count85
\oddhead=\toks41
\evenhead=\toks42
\titleoddhead=\toks43
\titleevenhead=\toks44
\noVoddhead=\toks45
\noVevenhead=\toks46
\oddfoot=\toks47
\evenfoot=\toks48
\titleevenfoot=\toks49
\titleoddfoot=\toks50
\noVoddfoot=\toks51
\noVevenfoot=\toks52
) (c:/Program Files/PTXprint/ptx2pdf/ptx-cropmarks.tex
\topcr@p=\box49
\bottomcr@p=\box50
\pdfcropwidth=\dimen81
\pdfcropheight=\dimen82
\tabheight=\dimen83
\tabwidth=\dimen84
\TabsStart=\dimen85
\TabsEnd=\dimen86
\NumTabs=\count86
\gp@boxN=\box51
\gp@boxL=\box52
\gp@boxR=\box53
\b@rder=\box54
\instopcr@p=\box55
\insbottomcr@p=\box56
\sp@newidth=\dimen87
\bl@eds=\dimen88
) (c:/Program Files/PTXprint/ptx2pdf/ptx-toc.tex
\t@cfile=\write2
\tocc@l=\count87
\t@ccount=\count88
\l@drsbox=\box57
) (c:/Program Files/PTXprint/ptx2pdf/ptx-tables.tex
\t@bleinserts=\box58
\s@vedm@rks=\toks53
\s@vedmarkcount=\count89
\t@blehsize=\dimen89
\cellb@x=\box59
\t@talwidth=\dimen90
\trmargin=\dimen91
\linec@unt=\count90
\lct@mp=\count91
\sp@re=\dimen92
\exc@ss=\dimen93
\thr@shold=\dimen94
\nth@line=\count92
\tabler@ws=\count93
\maxtablec@l=\count94
\tablec@l=\count95
\@col=\count96
\@row=\count97
\allocatedtablec@ls=\count98
) (c:/Program Files/PTXprint/ptx2pdf/ptx-triggers.tex
\trigg@rchecks=\toks54
\p@rnum=\count99
) (c:/Program Files/PTXprint/ptx2pdf/ptx-adj-list.tex
\@djparindex=\count100
\@djlist=\read4
\curr@djpar=\count101
) (c:/Program Files/PTXprint/ptx2pdf/ptx-pic-list.tex
\p@clistsuff=\count102
\p@clistentries=\count103
\p@clistused=\count104
\p@cusecheck=\toks55
\p@clist=\read5
) (c:/Program Files/PTXprint/ptx2pdf/ptx-cutouts.tex
\@numcuts=\count105
\@parshapelines=\count106
\@index=\count107
\@line=\count108
\@after=\count109
\@until=\count110
\@width=\dimen95
\@indent=\dimen96
\@hsize=\dimen97
) (c:/Program Files/PTXprint/ptx2pdf/ptx-callers.tex
\c@llernum=\count111
\numc@llers=\count112
\n@tepages=\write3
\n@tepagetest=\read6
\AutoCallerStartChar=\count113
\AutoCallerNumChars=\count114
) (c:/Program Files/PTXprint/ptx2pdf/ptx-figure.tex
\bottomins=\insert252
\verybottomins=\insert251
\topleftins=\insert250
\toprightins=\insert249
\bottomleftins=\insert248
\bottomrightins=\insert247
\tmpcountB=\count115
\c@ptionbox=\box60
\FigCreditPadding=\dimen98
\FigCreditOverEdgeV=\dimen99
\FigCreditOverEdgeH=\dimen100
\PicPath=\toks56
\newpicb@x=\box61
\picb@x=\box62
\picb@xR=\box63
\wholepagepic=\box64
\p@ramnumber=\count116
\notim@gecount=\count117
\p@cinswid=\dimen101
\p@cwidth=\dimen102
\p@cheight=\dimen103
\p@chshift=\dimen104
\otherinsht=\dimen105
\picl@ctest=\read7
\picp@ges=\write4
\onship@ut=\toks57
) (c:/Program Files/PTXprint/ptx2pdf/ptxplus-character-kerning.tex
\quotekernamount=\dimen106
ch> DefineActiveChar: 8216
ch> DefineActiveChar: 8217
ch> DefineActiveChar: 8220
ch> DefineActiveChar: 8221
) (c:/Program Files/PTXprint/ptx2pdf/ptx-unicode.tex
\KclassVir=\XeTeXcharclass4
\KclassCM=\XeTeXcharclass5
\KclassNum=\XeTeXcharclass6
\KclassArabL=\XeTeXcharclass7
\KclassArabR=\XeTeXcharclass8
\KclassArabD=\XeTeXcharclass9
\KclassArabU=\XeTeXcharclass10
) (c:/Program Files/PTXprint/ptx2pdf/ptx-extended.tex
\extb@x=\box65
\extchunkb@x=\box66
\sid@barnotes=\box67
\old@bx=\toks58
\feintb@xnum=\count118
\sb@rwidth=\dimen107
\sb@rchunkh@ight=\dimen108
\sb@rus@dheightl=\dimen109
\sb@rus@dheightr=\dimen110
) (c:/Program Files/PTXprint/ptx2pdf/ptx-borders.tex
\b@rderbox=\box68
\minblackline=\dimen111
\mincolourline=\dimen112
\minwhiteline=\dimen113
) (c:/Program Files/PTXprint/ptx2pdf/ptx-labels.tex) (c:/Program Files/PTXprint/ptx2pdf/ptx-output.tex
\RHruleposition=\dimen114
\t@xttrialheight=\dimen115
\partial=\box69
\ornXFids=\count119
\ornXobjects=\box70
\galley=\box71
\galleypenalty=\count120
\trialheight=\dimen116
\lastd@pth=\dimen117
\s@vedpage=\box72
\availht=\dimen118
\shortavail=\dimen119
\colhtA=\dimen120
\colhtB=\dimen121
\colA=\box73
\colB=\box74
\loopcount=\count121
\availA=\dimen122
\availB=\dimen123
\b@lbestavail=\dimen124
\b@lbestdiff=\dimen125
\t@vailht=\dimen126
\sh@vedim=\dimen127
\sh@venotes=\toks59
\coln@tebox=\box75
\n@tesbox=\box76
\n@tesoverrun=\box77
\bestavailht=\dimen128
\und@rfill=\dimen129
\columnshift=\dimen130
\ruleshift=\dimen131
\ColumnGutterRuleSkip=\dimen132
\RuleThickness=\dimen133
\StudyColumnGutterRuleSkip=\dimen134
\t@mpfile=\read8
) (c:/Program Files/PTXprint/ptx2pdf/ptx-plugins.tex)
\pdfp@ges=\count122
\whichp@ge=\count123
\im@gecount=\count124
\totalp@ges=\count125
\badspacepenalty=\count126
) (c:/Program Files/PTXprint/ptx2pdf/ptx-ptxprint.tex) Reading Paratext stylesheet "usfm_sb.sty" ()... [\id ] [\usfm ] [\ide ] [\h ] [\h1 ] [\h2 ] [\h3 ] [\toc1 ] [\toc2 ] [\toc3 ] [\toca1 ] [\toca2 ] [\toca3 ] [\rem ] [\sts ] [\restore ] [\imt ] [\imt1 ] [\imt2 ] [\imt3 ] [\imt4 ] [\imte ] [\imte1 ] [\imte2 ] [\is ] [\is1 ] [\is2 ] [\iot ] [\io ] [\io1 ] [\io2 ] [\io3 ] [\io4 ] [\ior ] [\ip ] [\im ] [\ipi ] [\imi ] [\ili ] [\ili1 ] [\ili2 ] [\ipq ] [\imq ] [\ipr ] [\ib ] [\iq ] [\iq1 ] [\iq2 ] [\iq3 ] [\iex ] [\iqt ] [\ie ] [\c ] [\ca ] [\cp ] [\cl ] [\cd ] [\v ] [\va ] [\vp ] [\p ] [\m ] [\po ] [\pr ] [\cls ] [\pmo ] [\pm ] [\pmc ] [\pmr ] [\pi ] [\pi1 ] [\pi2 ] [\pi3 ] [\pc ] [\mi ] [\nb ] [\q ] [\q1 ] [\q2 ] [\q3 ] [\q4 ] [\qc ] [\qr ] [\qs ] [\qa ] [\qac ] [\qm ] [\qm1 ] [\qm2 ] [\qm3 ] [\qd ] [\b ] [\mt ] [\mt1 ] [\mt2 ] [\mt3 ] [\mt4 ] [\mte ] [\mte1 ] [\mte2 ] [\ms ] [\mse ] [\ms1 ] [\ms2 ] [\ms2e ] [\ms3 ] [\ms3e ] [\mr ] [\s ] [\s1 ] [\s1e ] [\s2 ] [\s2e ] [\s3 ] [\s3e ] [\s4 ] [\s4e ] [\sr ] [\r ] [\sp ] [\d ] [\sd ] [\sd1 ] [\sd2 ] [\sd3 ] [\sd4 ] [\tr ] [\th1 ] [\th2 ] [\th3 ] [\th4 ] [\th5 ] [\th6 ] [\th7 ] [\th8 ] [\tc1 ] [\tc2 ] [\tc3 ] [\tc4 ] [\tc5 ] [\tc6 ] [\tc7 ] [\tc8 ] [\thc1 ] [\thc2 ] [\thc3 ] [\thc4 ] [\thc5 ] [\thc6 ] [\thc7 ] [\thc8 ] [\tcc1 ] [\tcc2 ] [\tcc3 ] [\tcc4 ] [\tcc5 ] [\tcc6 ] [\tcc7 ] [\tcc8 ] [\thr1 ] [\thr2 ] [\thr3 ] [\thr4 ] [\thr5 ] [\thr6 ] [\thr7 ] [\thr8 ] [\tcr1 ] [\tcr2 ] [\tcr3 ] [\tcr4 ] [\tcr5 ] [\tcr6 ] [\tcr7 ] [\tcr8 ] [\lh ] [\li ] [\li1 ] [\li2 ] [\li3 ] [\li4 ] [\lf ] [\lim ] [\lim1 ] [\lim2 ] [\lim3 ] [\lim4 ] [\litl ] [\lik ] [\liv ] [\liv1 ] [\liv2 ] [\liv3 ] [\liv4 ] [\f
\note-f=\insert246
\notesave1-f=\box78
\notesave2-f=\box79
\refn@te-f=\count127
 ] [\fe
\note-fe=\insert245
\notesave1-fe=\box80
\notesave2-fe=\box81
\refn@te-fe=\count128
 ] [\fr ] [\ft ] [\fk ] [\fq ] [\fqa ] [\fl ] [\fw ] [\fp ] [\fs ] [\fv ] [\fdc ] [\fm ] [\x
\note-x=\insert244
\notesave1-x=\box82
\notesave2-x=\box83
\refn@te-x=\count129
 ] [\xo ] [\xop ] [\xt ] [\xta ] [\xk ] [\xq ] [\xot ] [\xnt ] [\xdc ] [\rq ] [\ef
\note-ef=\insert243
\notesave1-ef=\box84
\notesave2-ef=\box85
\refn@te-ef=\count130
 ] [\ex
\note-ex=\insert242
\notesave1-ex=\box86
\notesave2-ex=\box87
\refn@te-ex=\count131
 ] [\esb ] [\esbe ] [\erq ] [\erqe ] [\cat ] [\qt ] [\nd ] [\tl ] [\dc ] [\bk ] [\sig ] [\pn ] [\png ] [\addpn ] [\wj ] [\k ] [\sls ] [\ord ] [\add ] [\lit ] [\no ] [\it ] [\bd ] [\bdit ] [\em ] [\sc ] [\sup ] [\pb ] [\fig ] [\jmp ] [\pro ] [\rb ] [\w ] [\wh ] [\wg ] [\wa ] [\ndx ] [\periph ] [\p1 ] [\p2 ] [\k1 ] [\k2 ] [\xtSee ] [\xtSeeAlso ] [\qt-s ] [\qt1-s ] [\qt2-s ] [\qt3-s ] [\qt4-s ] [\qt5-s ] [\ts-s ] [\ph ] [\ph1 ] [\ph2 ] [\ph3 ] [\phi ] [\tr1 ] [\tr2 ] [\ps ] [\psi ] [\wr ] [\pub ] [\toc ] [\pref ] [\intro ] [\conc ] [\glo ] [\idx ] [\maps ] [\cov ] [\spine ] [\pubinfo ] [\zpa-xb ] [\zpa-xc ] [\zpa-xv ] [\zpa-d ] Reading Paratext stylesheet "ptx2pdf.sty" ()... [\k [\imt [\imt1 [\imt2 [\imt3 [\imt4 [\imte [\imte1 [\imte2 [\is [\is1 [\is2 [\iot [\io1 [\io2 [\io3 [\io4 [\ip [\im [\ipi [\imi [\ili [\ili1 [\ili2 [\ipq [\imq [\ipr [\ib [\iq [\iq1 [\iq2 [\iq3 [\iex [\ie [\mt [\mt1 [\mt2 [\mt3 [\mt4 [\p [\m [\ms [\b [\pi [\pi1 [\pi2 [\pi3 [\pc [\mi [\nb [\pn [\nd [\s [\s1 [\s1e [\s2 [\s2e [\s3 [\s3e [\s4 [\s4e [\sr [\d [\lh [\li [\li1 [\li2 [\li3 [\li4 [\pb [\q [\q1 [\q2 [\q3 [\q4 [\pi [\pi1 [\pi2 [\pi3 [\tr [\p1 [\p2 [\v [\f [\fr [\fp ] [\fq [\fqa [\fk [\ft [\fv [\fm [\fdc [\x [\xo [\xq [\xk [\xdc [\xot [\xnt [\xt [\iqt [\pmo [\pm [\pmc [\qs [\rq [\pro [\wr [\wh [\wg [\wl ] [\fig [\periph [\rem [\rb ] [\it [\sc [\no [\bd [\bdit [\em [\cat [\err ] [\inc ] [\vrs ] [\ref ] [\refnp ] [\rep ] [\mod ] [\qt-s [\ampersand ] [\asterisk ] [\circumflex ] [\dollar ] [\dopagenums ] [\zfooter ] [\hash ] [\nopagenums ] [\percent ] [\resetpagenums ] [\space ] [\zNeedOddPage ] [\zNeedEvenPage ] [\zNeedQuadPage ] [\xts ] [\xti ] [\gloss|rb ] [\zthumbtab ] [\cat:colophon|esb [\zimagecopyrights ] [\zfiga ] [\zifvarset ] [\zifhook ] [\ztruetext ] [\zfalsetext ] [\ztoc ] [\zfillsignature ] [\zvar ] [\zgetperiph ] [\zISBNbarcode ] [\x-credit [\Dark|x-credit [\Light|x-credit [\None|x-credit [\toc3 [\zbl ] [\zrule ] [\zmakeinsert ] [\zrule ] [\zmvm ] [\zqrcode ] [\zgap ] [\zsetref ] [\zlabel ] [\zpage ] [\zref ] [\zcustommark ] [\zcustomtopmark ] [\zcustombotmark ] [\zcustomfirstmark ] [\zornament ] [\textborder [\id:INT|textborder [\id:GLO|textborder [\id:GLO|p ] [\strong-s ] [\strong-s+li ] [\strong-s+m ] [\wg+strong-s ] [\wh+strong-s ] [\wl+strong-s ] [\xt+strong-s ] [\k+strong-s ] [\cat:toc|tr [\cat:toc|tc1 [\cat:box|esb [\zglm ] [\zpmkr ] [\th1 [\th2 [\th3 [\th4 [\th5 [\th6 [\th7 [\th8 [\tc1 [\cat:toc|tc1 [\tc2 [\tc3 [\tc4 [\tc5 [\tc6 [\tc7 [\tc8 [\toc1 [\toc2 [\toc3 [\ldrs ] [\cat:coverwhole|esb [\cat:coverspine|esb [\cat:coverfront|esb [\cat:coverback|esb [\cat:coverback|m ] [\cat:ISBNbox|esb [\zcolsync ] [\cat:coverfront|mt1 ] [\cat:coverfront|mt2 ] [\cat:coverspine|mt1 ] [\cat:coverspine|mt2 ] [\cat:titlebox|esb [\cat:headingsbox|esb [\zbn ] [\zbn2 ] Reading Paratext stylesheet "../../../shared/ptxprint/PublikasiSelaru-Rut/ptxprint.sty" ()... [\Dark|x-credit [\Light|x-credit [\None|x-credit [\b [\f [\fe [\fig [\fk [\fl [\fm [\fp [\fq [\fqa [\fr [\ft [\fv [\fw [\h [\ib [\ili [\ili1 [\ili2 [\im [\imi [\imq [\imt [\imt1 [\imte [\io [\io1 [\io2 [\io3 [\io4 [\ior [\ip [\ipc ] [\ipi [\ipq [\ipr [\iq [\iq1 [\iq2 [\iq3 [\is [\is1 [\is2 [\k2 [\li [\li1 [\li2 [\li3 [\li4 [\lim [\liv [\ms [\mt [\mt1 [\mt2 [\mt3 [\mte [\p [\periph [\pi [\pi1 [\pi2 [\pi3 [\pr [\q [\q1 [\q2 [\q3 [\qm [\r [\rq [\s [\s1 [\s3 [\s3e [\s4 [\s4e [\sc [\sd [\sp [\tc1 [\tc2 [\tc3 [\tc4 [\tc5 [\tc6 [\tc7 [\tc8 [\tcc1 [\tcc2 [\tcc3 [\tcc4 [\tcc5 [\tcc6 [\tcc7 [\tcc8 [\tcr1 [\tcr2 [\tcr3 [\tcr4 [\tcr5 [\tcr6 [\tcr7 [\tcr8 [\textborder [\th1 [\th2 [\th3 [\th4 [\th5 [\th6 [\th7 [\th8 [\thc1 [\thc2 [\thc3 [\thc4 [\thc5 [\thc6 [\thc7 [\thc8 [\thr1 [\thr2 [\thr3 [\thr4 [\thr5 [\thr6 [\thr7 [\thr8 [\tl [\tr [\v [\x [\x-credit [\xk [\xnt [\xo [\xop [\xot [\xq [\xt [\xta [\zimagecopyrights
\intercharskip=\skip22
 (c:/My Paratext 9 Projects/SLU/local/ptxprint/PublikasiSelaru-Rut/SLU_PublikasiSelaru-Rut_RUT_ptxp.notepages)
\openout3 = `SLU_PublikasiSelaru-Rut_RUT_ptxp.notepages'.


(using pictures from list "SLU_PublikasiSelaru-Rut_RUT_ptxp.piclist")
\langund=\language1
snippet 1
Reading optional file "../../../shared/ptxprint/PublikasiSelaru-Rut/ptxprint-mods.tex"
 (../../../shared/ptxprint/PublikasiSelaru-Rut/ptxprint-mods.tex) ! Parent style "Vectorian2" referenced for borders by "textborder" does not exist!
Baselineskip for p was undefined, now set to 14.89984pt(14.89984pt)
lineskiplimit=-11.17488pt
\baselineskip =14.89984pt, topskip=14.89984pt
includepdf C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf pages=10
INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [1] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [2] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [3] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [4] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [5] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [6] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [7] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [8] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [9] INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" INPUTFILE: "C:/My Paratext 9 Projects/SLU/shared/BAGIAN DEPAN-RUT-baru.pdf" [10] ptxfile  monoglot, The colour Rule specified for Graphpaper major line is thinner than the supplied limit ( = 0.4pt  < 0.5pt) near start The colour Rule specified for Graphpaper minor line is thinner than the supplied limit ( = 0.25pt  < 0.5pt) near start The colour Rule specified for Note space minor line is thinner than the supplied limit ( = 0.3pt  < 0.5pt) near start (c:/My Paratext 9 Projects/SLU/local/ptxprint/PublikasiSelaru-Rut/SLU_PublikasiSelaru-Rut_RUT_ptxp.delayed)
\openout0 = `SLU_PublikasiSelaru-Rut_RUT_ptxp.parlocs'.

\endn@te-fe=\box88
\savecolinsert@tLcol=\box89
\savecolinsert@tLchunk=\box90
\savecolinsert@tRcol=\box91
\savecolinsert@tRchunk=\box92
\savecolinsert@bLcol=\box93
\savecolinsert@bLchunk=\box94
\savecolinsert@bRcol=\box95
\savecolinsert@bRchunk=\box96
\savebottominscol=\box97
\savebottominschunk=\box98
\saveverybottominscol=\box99
\saveverybottominschunk=\box100
\savetopinscol=\box101
\savetopinschunk=\box102
 [\cat:toc|tc1 ] [\cat:toc|tc2 ] [\cat:toc|tc3 ] [\cat:toc|tc4 ]
(no adjustment list "../../../shared/ptxprint/PublikasiSelaru-Rut/AdjLists/.adj" found)
(no picture list "tmpPicLists/.piclist" found)
 (c:/My Paratext 9 Projects/SLU/local/ptxprint/PublikasiSelaru-Rut/SLU_PublikasiSelaru-Rut_RUT_ptxp.picpages)
\openout4 = `SLU_PublikasiSelaru-Rut_RUT_ptxp.picpages'.

 ptxfile 08RUTSLU-PublikasiSelaru-Rut.SFM monoglot, The colour Rule specified for Graphpaper major line is thinner than the supplied limit ( = 0.4pt  < 0.5pt) near start The colour Rule specified for Graphpaper minor line is thinner than the supplied limit ( = 0.25pt  < 0.5pt) near start The colour Rule specified for Note space minor line is thinner than the supplied limit ( = 0.3pt  < 0.5pt) near start
(no adjustment list "../../../shared/ptxprint/PublikasiSelaru-Rut/AdjLists/08RUTSLU-PublikasiSelaru-Rut.SFM.adj" found)
(no picture list "tmpPicLists/08RUTSLU-PublikasiSelaru-Rut.SFM.piclist" found)
 (./08RUTSLU-PublikasiSelaru-Rut.SFM [1] First chapter for RUT
converted picture placement "bl" to "b" in single-column layout
INPUTFILE: "./tmpPics/co00951.jpg" -> "./tmpPics/co00951.jpg" [2] [3] INPUTFILE: "./tmpPics/co00956.jpg" -> "./tmpPics/co00956.jpg" [4] INPUTFILE: "./tmpPics/co00958.jpg" -> "./tmpPics/co00958.jpg" [5] INPUTFILE: "./tmpPics/lb00102.jpg" -> "./tmpPics/lb00102.jpg" [6] INPUTFILE: "./tmpPics/co00961.jpg" -> "./tmpPics/co00961.jpg" [7] INPUTFILE: "./tmpPics/co00964.jpg" -> "./tmpPics/co00964.jpg" [8] [9]
converted picture placement "tl" to "t" in single-column layout
INPUTFILE: "./tmpPics/co00968.jpg" -> "./tmpPics/co00968.jpg" INPUTFILE: "./tmpPics/hk00099.jpg" -> "./tmpPics/hk00099.jpg"
! Undefined control sequence.
\d@figureCut ...\advance \dimen 1 by \c@tskipfrac 
                                                  \baselineskip \dimen 2=\wd...
\pl@cefigure ...fx \picl@c \loc@Cut \d@figureCut 0
                                                  \fi \ifvoid 0\else \messag...
\d@figure ...gnored.}\fi \fi \iftemp \pl@cefigure 
                                                  \fi \let \sb@rmarker \orig...
\ch@ckN@xtPicid ... {\x@ \d@figure \x@ {\p@cspec }
                                                  }\let \cnpicr@pe@t \ch@ckN...
\ch@ckpiclist ... \p@clistsuff =1 \ch@ckN@xtPicid 
                                                  \ifdiglot \let \p@cref =\d...
\nxt ->\the \prev@rsehooks 
                           \spl@tprintableverse \pdfv@rsemark \ifc@ncelfirst...
...
l.103 \v 21 L
             emadendye Rut lyosu huruk ti ryana ma byohe, “Eno! Iry desike b... 
Here is how much of TeX's memory you used:
 8908 strings out of 495008
 114654 string characters out of 12441576
 258123 words of memory out of 5000000
 12714 multiletter control sequences out of 15000+600000
 4898 words of font info for 35 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 65521
 29i,14n,32p,1333b,564s stack positions out of 30000i,1000n,20000p,200000b,200000s

Output written on SLU_PublikasiSelaru-Rut_RUT_ptxp.xdv (19 pages, 140672 bytes).

**Comment by davidc86** [comment]
And it still does not remember the specified (c) text settings for the pictures. Exiting PTXprint and reopening it, the dialog specs for (c) text was blank.
